export const pages = [
  { title: "Intro", path: "/" },
  { title: "Digital History", path: "/digital-history" },
  { title: "Internet History", path: "/internet-history" },
  { title: "New Narratives & SEO", path: "/narratives-and-seo" },
  { title: "Traditional vs Digital", path: "/traditional-and-digital" },
  { title: "Open Source & Data", path: "/open-source-data" },
  { title: "Git & GitHub", path: "/git-and-github" },
  { title: "Datasets & Databases", path: "/datasets-databases" },
  { title: "PostgreSQL Startup", path: "/postgresql-startup" },
  { title: "PostgreSQL Design", path: "/postgresql-design" },
  { title: "PostgreSQL Queries", path: "/postgresql-queries" },
  { title: "PostgreSQL with Tableau", path: "/postgresql-and-tableau" },
  { title: "OCR, Text Search, & Ngrams", path: "/ocr-text-search" },
  { title: "Text Analysis with Voyant", path: "/text-analysis-with-voyant" },
  { title: "Timelines", path: "/timelines" },
  { title: "Spatial Analysis", path: "/spatial-analysis" },
  { title: "StoryMaps", path: "/storymaps" },
  { title: "Palladio Maps", path: "/palladio-maps" },
  { title: "Palladio Networks", path: "/palladio-networks" },
  { title: "Public Digital History", path: "/digital-public-history" },
  { title: "Omeka, part I", path: "/omeka-1" },
  { title: "Omeka, part II", path: "/omeka-2" },
  { title: "Crowdsourcing History", path: "/crowdsourcing-history" },
  { title: "Video Games", path: "/video-games-and-history" },
];
